# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mock_pb2 as mock__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MockModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictNext = channel.unary_unary(
                '/mock.MockModel/PredictNext',
                request_serializer=mock__pb2.PredictRequest.SerializeToString,
                response_deserializer=mock__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/mock.MockModel/Health',
                request_serializer=mock__pb2.HealthRequest.SerializeToString,
                response_deserializer=mock__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Retrain = channel.unary_unary(
                '/mock.MockModel/Retrain',
                request_serializer=mock__pb2.RetrainRequest.SerializeToString,
                response_deserializer=mock__pb2.RetrainResponse.FromString,
                _registered_method=True)


class MockModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictNext(self, request, context):
        """PredictNext returns the most likely next syscall given a context sequence.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrain(self, request, context):
        """Trigger retraining from fresh corpus.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MockModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictNext': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictNext,
                    request_deserializer=mock__pb2.PredictRequest.FromString,
                    response_serializer=mock__pb2.PredictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=mock__pb2.HealthRequest.FromString,
                    response_serializer=mock__pb2.HealthResponse.SerializeToString,
            ),
            'Retrain': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrain,
                    request_deserializer=mock__pb2.RetrainRequest.FromString,
                    response_serializer=mock__pb2.RetrainResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mock.MockModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mock.MockModel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MockModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictNext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mock.MockModel/PredictNext',
            mock__pb2.PredictRequest.SerializeToString,
            mock__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mock.MockModel/Health',
            mock__pb2.HealthRequest.SerializeToString,
            mock__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retrain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mock.MockModel/Retrain',
            mock__pb2.RetrainRequest.SerializeToString,
            mock__pb2.RetrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
