# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mock.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'mock.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmock.proto\x12\x04mock\"\x1f\n\x0ePredictRequest\x12\r\n\x05\x63\x61lls\x18\x01 \x03(\t\"a\n\x0fPredictResponse\x12\x16\n\x0epredicted_call\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\"\n\x05top_k\x18\x03 \x03(\x0b\x32\x13.mock.CandidateCall\",\n\rCandidateCall\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\"\x0f\n\rHealthRequest\"f\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x12\n\nvocab_size\x18\x02 \x01(\x03\x12\x18\n\x10training_samples\x18\x03 \x01(\x03\x12\x15\n\rmodel_version\x18\x04 \x01(\t\"$\n\x0eRetrainRequest\x12\x12\n\ncorpus_dir\x18\x01 \x01(\t\"I\n\x0fRetrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0csamples_used\x18\x03 \x01(\x03\x32\xb4\x01\n\tMockModel\x12:\n\x0bPredictNext\x12\x14.mock.PredictRequest\x1a\x15.mock.PredictResponse\x12\x33\n\x06Health\x12\x13.mock.HealthRequest\x1a\x14.mock.HealthResponse\x12\x36\n\x07Retrain\x12\x14.mock.RetrainRequest\x1a\x15.mock.RetrainResponseB4Z2github.com/google/syzkaller/tools/mock_model/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/google/syzkaller/tools/mock_model/proto'
  _globals['_PREDICTREQUEST']._serialized_start=20
  _globals['_PREDICTREQUEST']._serialized_end=51
  _globals['_PREDICTRESPONSE']._serialized_start=53
  _globals['_PREDICTRESPONSE']._serialized_end=150
  _globals['_CANDIDATECALL']._serialized_start=152
  _globals['_CANDIDATECALL']._serialized_end=196
  _globals['_HEALTHREQUEST']._serialized_start=198
  _globals['_HEALTHREQUEST']._serialized_end=213
  _globals['_HEALTHRESPONSE']._serialized_start=215
  _globals['_HEALTHRESPONSE']._serialized_end=317
  _globals['_RETRAINREQUEST']._serialized_start=319
  _globals['_RETRAINREQUEST']._serialized_end=355
  _globals['_RETRAINRESPONSE']._serialized_start=357
  _globals['_RETRAINRESPONSE']._serialized_end=430
  _globals['_MOCKMODEL']._serialized_start=433
  _globals['_MOCKMODEL']._serialized_end=613
# @@protoc_insertion_point(module_scope)
